name: Simple Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Find and Install Dependencies
        run: |
          # מחפש את התיקייה שבה נמצא package.json ונכנס אליה
          TARGET_DIR=$(find . -name "package.json" -exec dirname {} \;)
          echo "Found package.json in $TARGET_DIR"
          cd $TARGET_DIR
          npm install

      - name: Build APK
        run: |
          # מחפש את התיקייה שבה נמצא app.json ונכנס אליה לבנייה
          TARGET_DIR=$(find . -name "app.json" -exec dirname {} \;)
          cd $TARGET_DIR
          eas build -p android --profile preview --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
